version: '3.7'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./site:/var/www/html
      - ./hrlr:/var/www/html/wp-content/themes/hrlr
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql

  cli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    deploy:
      restart_policy:
        condition: none
    user: xfs
    command: >
      /bin/sh -c '
        sleep 10;
        wp core install --path="/var/www/html" --url="http://localhost:8080" --title="HRLR" --admin_user=admin --admin_password=admin --admin_email=admin@example.org;
        wp plugin install mammoth-docx-converter --activate;
        wp theme activate hrlr'
    volumes:
      - ./site:/var/www/html
